### ISSUE TITLE
Hand model not shown in rviz

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface-ethercat#24]
The hand model is not shown in rviz, although the collision model mode is shown and is correctly reflecting the hand position.

This is true for both hands.

**Comment by ugocupcic** [comment]
Check sr_description against F_moveit it's probably a problem with the dae
that has been fixed in the F_moveit branch.

On 8 July 2013 12:56, toliver notifications@github.com wrote:

> The hand model is not shown in rviz, although the collision model mode is
> shown and is correctly reflecting the hand position.
> 
> This is true for both hands.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ros-interface-ethercat/issues/24
> .

## 

Ugo Cupcic | Shadow Robot Company | ugo@shadowrobot.com
Senior Software Engineer | 251 Liverpool Road |
need a Hand? | London N1 1LX | +44 20 7700 2487
http://www.shadowrobot.com/hand/ @shadowrobot

## 

----------------------------------------------------------------*
Shadow Robot Company Ltd.*
Registered Number 3308007 (England & Wales)

## Office Address 251 Liverpool Road, N1 1LX, UK
